"""add otp_codes table

Revision ID: 1353470af3b3
Revises: 40914e1d0c3a
Create Date: 2026-04-08 01:10:52.718565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1353470af3b3'
down_revision = '40914e1d0c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_expires_at'))

    op.drop_table('otp_codes')
    # ### end Alembic commands ###
