"""add likes table

Revision ID: 40914e1d0c3a
Revises: 69ff9ce378b2
Create Date: 2026-04-04 22:54:38.717757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40914e1d0c3a'
down_revision = '69ff9ce378b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
