"""add likes_count column to posts table

Revision ID: 69ff9ce378b2
Revises: bce670700cbd
Create Date: 2026-04-04 21:44:26.336067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ff9ce378b2'
down_revision = 'bce670700cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.create_index(batch_op.f('ix_posts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_user_id'))
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
