"""refactor unique indexes

Revision ID: 6b1e724eb742
Revises: 4bd1d3fb9b83
Create Date: 2026-03-04 01:59:12.488841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1e724eb742'
down_revision = '4bd1d3fb9b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_index('uq_users_email', ['email'], unique=True)
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.create_index('uq_users_username', ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_username')
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])
        batch_op.drop_index('uq_users_email')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###
