"""add created_at to posts

Revision ID: 9db5df3f9008
Revises: 07cb5df9f4ec
Create Date: 2026-03-19 09:32:12.518762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db5df3f9008'
down_revision = '07cb5df9f4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
